---
#AmazonLinux2 EPEL
- name: AmazonLinux2 EPEL Release 7 (RedHat)
  set_fact:
    ansible_distribution_major_version: 7
  when: ansible_distribution == "Amazon"

- name: Check if EPEL repo is already configured.(RedHat)
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result
  when: ansible_os_family == 'RedHat'

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: ansible_os_family == 'RedHat' and not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: ansible_os_family == 'RedHat' and not epel_repofile_result.stat.exists

- name: Install fail2ban (RedHat).
  package:
    name: fail2ban
    state: present
    enablerepo: epel
  when: ansible_os_family == 'RedHat'

- name: Install fail2ban (Debian).
  package:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy fail2ban custom configuration file into place.
  template:
    src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: started
    enabled: true
