---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


# Upgrade and update packages
- include_tasks: security_updates.yml

# Fail2Ban
- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

# SSH
- include_tasks: ssh.yml

