---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "libertxyz/docker-ansible-${MOLECULE_DISTRO}:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
